version: "3.9"
services:
  app:
    build: .
    image: python:3.10-alpine
    command: python main.py
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 5001:5000

#docker-compose.yaml
#docker-compose up -d -> uruchamianie kontenerów
#docker-compose ps -> sprawdzanie stanu kontenrów
#docker-compose exec app /bin/sh -> wchodzenie do kontenera
